#ifndef ANTMOUSE_H_
#define ANTMOUSE_H_

#define ANTMOUSE_IRQ_NUMBER 84
#define ANTMOUSE_BASE 0xF8F03000
#define ANTMOUSE_SIZE 0x100

#define ANTMOUSE_HEIGHT 480
#define ANTMOUSE_WIDTH 800

#define XREG 0
#define YREG 1
#define LEFTBTN 2
#define INTERRUPT 3

#endif
